apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.durp.info/durfy/homelab/gitops.git
    targetRevision: main
    path: infra/traefik
  destination:
    namespace: traefik
    name: in-cluster
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    automated:
      prune: true
      selfHeal: true  
    syncOptions:
      - CreateNamespace=true 

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-dmz
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.durp.info/durfy/homelab/gitops.git
    targetRevision: main
    path: dmz/traefik
  destination:
    namespace: traefik
    name: dmz
  syncPolicy:
    #    managedNamespaceMetadata:
    #      labels:
    #        istio-injection: enabled
    automated:
      prune: true
      selfHeal: true  
    syncOptions:
      - CreateNamespace=true 

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.durp.info/durfy/homelab/gitops.git
    targetRevision: main
    path: dev/traefik
  destination:
    namespace: traefik
    name: dev
  syncPolicy:
    #    managedNamespaceMetadata:
    #      labels:
    #        istio-injection: enabled
    automated:
      prune: true
      selfHeal: true  
    syncOptions:
      - CreateNamespace=true 

